type Lang = 'en' | 'ru'

const currentLang = ref<Lang>('en')

const translations: Record<string, Record<Lang, string>> = {
  'hero.title.1': { en: 'Return to', ru: 'Вернись в' },
  'hero.title.2': { en: 'Atreia', ru: 'Атрею' },
  'hero.desc': {
    en: 'Classic 3.9 Aion on dedicated European servers. No pay-to-win, no custom imbalances — the experience you remember.',
    ru: 'Классический Aion 3.9 на выделенных европейских серверах. Без доната, без кастомного дисбаланса — тот самый опыт.',
  },
  'hero.cta': { en: 'Start playing', ru: 'Начать играть' },
  'hero.explore': { en: 'Explore the realm', ru: 'Узнать больше' },
  'nav.realm': { en: 'Realm', ru: 'Мир' },
  'nav.news': { en: 'News', ru: 'Новости' },
  'nav.rankings': { en: 'Rankings', ru: 'Рейтинг' },
  'nav.siege': { en: 'Siege', ru: 'Осады' },
  'nav.wiki': { en: 'Wiki', ru: 'Wiki' },
  'nav.rank': { en: 'Rankings', ru: 'Рейтинг' },
  'nav.start': { en: 'Start', ru: 'Начать' },
  'start.title': { en: 'Start playing', ru: 'Начать играть' },
  'start.desc': { en: 'From zero to Atreia in under 10 minutes.', ru: 'От нуля до Атреи менее чем за 10 минут.' },
  'start.s1.title': { en: 'Create your account', ru: 'Создай аккаунт' },
  'start.s1.desc': { en: 'Quick registration — email and password. No phone number, no verification delays. Your account is ready instantly.', ru: 'Быстрая регистрация — email и пароль. Без номера телефона, без задержек. Аккаунт готов мгновенно.' },
  'start.s1.cta': { en: 'Register now', ru: 'Зарегистрироваться' },
  'start.s2.title': { en: 'Download the client', ru: 'Скачай клиент' },
  'start.s2.desc': { en: 'Our lightweight launcher downloads and patches the game automatically. Total size: ~8.2 GB. Average download time: 15-30 minutes on a decent connection.', ru: 'Наш лёгкий лаунчер автоматически скачает и пропатчит игру. Размер: ~8.2 ГБ. Среднее время загрузки: 15-30 минут.' },
  'start.s2.cta': { en: 'Download launcher', ru: 'Скачать лаунчер' },
  'start.s3.title': { en: 'Launch and play', ru: 'Запусти и играй' },
  'start.s3.desc': { en: 'Open the launcher, log in with your credentials, and hit Play. Choose Elyos or Asmodian, create your character, and enter Atreia.', ru: 'Открой лаунчер, войди с логином и паролем, нажми Play. Выбери Элийцев или Асмодиан, создай персонажа и войди в Атрею.' },
  'start.req.title': { en: 'System requirements', ru: 'Системные требования' },
  'start.req.min': { en: 'Minimum', ru: 'Минимальные' },
  'start.req.rec': { en: 'Recommended', ru: 'Рекомендуемые' },
  'start.faq.title': { en: 'Common issues', ru: 'Частые проблемы' },
  'start.faq.q1': { en: 'Launcher won\'t start', ru: 'Лаунчер не запускается' },
  'start.faq.a1': { en: 'Run as Administrator. Make sure antivirus is not blocking the file. Add the launcher folder to antivirus exceptions.', ru: 'Запусти от имени Администратора. Убедись, что антивирус не блокирует файл. Добавь папку лаунчера в исключения антивируса.' },
  'start.faq.q2': { en: 'Game crashes on character selection', ru: 'Игра вылетает на выборе персонажа' },
  'start.faq.a2': { en: 'Update your GPU drivers. If using an AMD card, disable Radeon Anti-Lag. Try running in windowed mode first.', ru: 'Обнови драйвера видеокарты. Если AMD — отключи Radeon Anti-Lag. Попробуй сначала в оконном режиме.' },
  'start.faq.q3': { en: 'High ping / lag', ru: 'Высокий пинг / лаги' },
  'start.faq.a3': { en: 'Server is in Frankfurt, Germany. If your ping is above 100ms, try a gaming VPN like ExitLag or Mudfish. Disable background downloads.', ru: 'Сервер в Франкфурте, Германия. Если пинг выше 100мс, попробуй gaming VPN (ExitLag, Mudfish). Отключи фоновые загрузки.' },
  'start.faq.q4': { en: 'SendLog error on launch', ru: 'Ошибка SendLog при запуске' },
  'start.faq.a4': { en: 'Delete the bin32/aion.bin.old file in your game folder. If it persists, run File Repair in the launcher.', ru: 'Удали файл bin32/aion.bin.old в папке игры. Если не помогло, запусти File Repair в лаунчере.' },
  'rank.title': { en: 'Rankings', ru: 'Рейтинг' },
  'rank.desc': { en: 'The strongest Daevas and most powerful Legions of Atreia.', ru: 'Сильнейшие даэвы и могущественные легионы Атреи.' },
  'rank.abyss': { en: 'Abyss ranking', ru: 'Рейтинг Бездны' },
  'rank.legions': { en: 'Legions', ru: 'Легионы' },
  'rank.statistics': { en: 'Statistics', ru: 'Статистика' },
  'rank.name': { en: 'Name', ru: 'Имя' },
  'rank.race': { en: 'Race', ru: 'Раса' },
  'rank.class': { en: 'Class', ru: 'Класс' },
  'rank.ap': { en: 'AP', ru: 'AP' },
  'rank.kills': { en: 'Kills', ru: 'Убийства' },
  'rank.level': { en: 'Level', ru: 'Уровень' },
  'rank.online_now': { en: 'Online now', ru: 'Онлайн сейчас' },
  'rank.total_chars': { en: 'Total characters', ru: 'Всего персонажей' },
  'rank.by_class': { en: 'Characters by class', ru: 'Персонажи по классам' },
  'rank.by_race': { en: 'Race balance', ru: 'Баланс рас' },
  'rank.back': { en: 'Back to home', ru: 'На главную' },
  'nav.signin': { en: 'Sign in', ru: 'Войти' },
  'nav.play': { en: 'Play Free', ru: 'Играть' },
  'stats.online': { en: 'Online', ru: 'Онлайн' },
  'stats.accounts': { en: 'Accounts', ru: 'Аккаунтов' },
  'stats.patch': { en: 'Patch', ru: 'Патч' },
  'stats.uptime': { en: 'Uptime', ru: 'Аптайм' },
  'realm.eyebrow': { en: 'What defines us', ru: 'Что нас отличает' },
  'realm.title': { en: 'Built for the ones who remember', ru: 'Для тех, кто помнит Атрею' },
  'feat.classic.title': { en: 'Authentic classic 3.9', ru: 'Аутентичный классик 3.9' },
  'feat.classic.desc': {
    en: 'No custom modifications. The same Aion you fell in love with — every quest, every instance, every mechanic faithful to the original.',
    ru: 'Без кастомных модификаций. Тот самый Aion — каждый квест, каждый инстанс, каждая механика верна оригиналу.',
  },
  'feat.pvp.title': { en: 'Active Abyss warfare', ru: 'Активный PvP в Бездне' },
  'feat.pvp.desc': { en: 'Daily sieges, Dredgion, and open-world fights around the clock.', ru: 'Ежедневные осады, Дредгион и PvP в открытом мире.' },
  'feat.fair.title': { en: 'Zero pay-to-win', ru: 'Без доната' },
  'feat.fair.desc': { en: 'Cosmetics shop only. Every item earned through gameplay.', ru: 'Только косметика в магазине. Всё добывается в игре.' },
  'feat.rates.title': { en: 'Fair mid-rate', ru: 'Честный мид-рейт' },
  'feat.rates.desc': { en: 'Balanced progression. Not too fast, not too slow.', ru: 'Сбалансированная прогрессия. Путь имеет значение.' },
  'feat.servers.title': { en: 'EU dedicated', ru: 'EU серверы' },
  'feat.servers.desc': { en: 'High-performance infrastructure. Sub-30ms for EU players.', ru: 'Высокопроизводительная инфраструктура. Пинг до 30мс для EU.' },
  'feat.team.title': { en: 'Active dev team', ru: 'Активная команда' },
  'feat.team.desc': { en: 'Weekly patches, monthly events. The server grows with its community.', ru: 'Еженедельные патчи, ежемесячные ивенты.' },
  'news.eyebrow': { en: 'Dispatches', ru: 'Новости' },
  'news.title': { en: 'From the frontlines', ru: 'С передовой' },
  'news.all': { en: 'All news', ru: 'Все новости' },
  'rankings.eyebrow': { en: 'Leaderboard', ru: 'Рейтинг' },
  'rankings.title': { en: 'Top Daevas', ru: 'Лучшие даэвы' },
  'rankings.rank': { en: 'Rank', ru: '#' },
  'rankings.character': { en: 'Character', ru: 'Персонаж' },
  'rankings.race': { en: 'Race', ru: 'Раса' },
  'rankings.class': { en: 'Class', ru: 'Класс' },
  'rankings.score': { en: 'Score', ru: 'Очки' },
  'rankings.status': { en: 'Status', ru: 'Статус' },
  'tab.pvp': { en: 'PvP', ru: 'PvP' },
  'tab.abyss': { en: 'Abyss', ru: 'Бездна' },
  'tab.online': { en: 'Online', ru: 'Онлайн' },
  'siege.eyebrow': { en: 'War council', ru: 'Военный совет' },
  'siege.title': { en: 'Siege schedule', ru: 'Расписание осад' },
  'cta.title.1': { en: 'Your war begins', ru: 'Твоя война' },
  'cta.title.2': { en: 'at the tower', ru: 'начинается здесь' },
  'cta.desc': { en: 'Pick your side. Ascend as a Daeva. The Abyss does not wait.', ru: 'Выбери сторону. Стань даэвой. Бездна не ждёт.' },
  'cta.button': { en: 'Create free account', ru: 'Создать аккаунт' },
  'server.status': { en: 'Server online', ru: 'Сервер онлайн' },
  'steps.title': { en: 'Start in 5 minutes', ru: 'Начни за 5 минут' },
  'steps.1.title': { en: 'Create account', ru: 'Создай аккаунт' },
  'steps.1.desc': { en: 'Quick registration. Email and password — that\'s it.', ru: 'Быстрая регистрация. Email и пароль — всё.' },
  'steps.2.title': { en: 'Download client', ru: 'Скачай клиент' },
  'steps.2.desc': { en: 'Lightweight launcher, auto-patching. ~8 GB.', ru: 'Лёгкий лаунчер с автопатчем. ~8 ГБ.' },
  'steps.3.title': { en: 'Enter Atreia', ru: 'Войди в Атрею' },
  'steps.3.desc': { en: 'Pick Elyos or Asmodian. Your war begins.', ru: 'Выбери Элийцев или Асмодиан. Твоя война начинается.' },
  'factions.title': { en: 'Choose your side', ru: 'Выбери сторону' },
  'factions.elyos': { en: 'Elyos', ru: 'Элийцы' },
  'factions.asmodian': { en: 'Asmodians', ru: 'Асмодиане' },
  'community.title': { en: 'Join the community', ru: 'Присоединяйся' },
  'community.desc': { en: 'Active Discord with 2,000+ members. Guilds recruiting, siege coordination, trade chat.', ru: 'Активный Discord с 2,000+ участников. Набор в легионы, координация осад, торговля.' },
  'community.cta': { en: 'Join Discord', ru: 'Зайти в Discord' },
  'announce.text': { en: 'Patch 3.9.7 is live — Dredgion fixes, class balance, new events.', ru: 'Патч 3.9.7 вышел — фиксы Дредгиона, баланс классов, новые ивенты.' },
  'announce.link': { en: 'Read more', ru: 'Подробнее' },
  'download.title': { en: 'Download & play', ru: 'Скачай и играй' },
  'download.size': { en: 'Client size: ~8.2 GB', ru: 'Размер клиента: ~8.2 ГБ' },
  'download.cta': { en: 'Download client', ru: 'Скачать клиент' },
  'download.launcher': { en: 'Launcher auto-patches to latest version', ru: 'Лаунчер автоматически обновится до последней версии' },
  'download.req': { en: 'System requirements', ru: 'Системные требования' },
  'download.os': { en: 'Windows 7 / 10 / 11', ru: 'Windows 7 / 10 / 11' },
  'download.cpu': { en: 'Intel i3 / AMD Ryzen 3', ru: 'Intel i3 / AMD Ryzen 3' },
  'download.ram': { en: '4 GB RAM', ru: '4 ГБ RAM' },
  'download.gpu': { en: 'GeForce GTX 660 / Radeon HD 7850', ru: 'GeForce GTX 660 / Radeon HD 7850' },
  'faq.title': { en: 'Questions & answers', ru: 'Вопросы и ответы' },
  'faq.q1': { en: 'What are the server rates?', ru: 'Какие рейты на сервере?' },
  'faq.a1': { en: 'Mid-rate: x3 EXP, x3 Kinah, x2 Drop, x2 AP. Enough to enjoy the journey without months of grind.', ru: 'Мид-рейт: x3 EXP, x3 Кинар, x2 Дроп, x2 AP. Достаточно чтобы наслаждаться игрой без месяцев гринда.' },
  'faq.q2': { en: 'Is there pay-to-win?', ru: 'Есть ли донат?' },
  'faq.a2': { en: 'No. The shop sells cosmetics, mounts, and convenience items only. No gear, no stones, no enchants.', ru: 'Нет. В магазине только косметика, маунты и удобства. Никакого снаряжения, камней или заточек.' },
  'faq.q3': { en: 'How do I start playing?', ru: 'Как начать играть?' },
  'faq.a3': { en: 'Register on the site, download the client (~8 GB), launch and log in. Takes about 5 minutes plus download time.', ru: 'Зарегистрируйся на сайте, скачай клиент (~8 ГБ), запусти и войди. Занимает 5 минут плюс время загрузки.' },
  'faq.q4': { en: 'Which patch version is the server?', ru: 'Какая версия патча на сервере?' },
  'faq.a4': { en: 'Classic 3.9 — the most beloved era of Aion. All instances, sieges, and mechanics from this patch are working.', ru: 'Классик 3.9 — самая любимая эра Aion. Все инстансы, осады и механики этого патча работают.' },
  'faq.q5': { en: 'Where is the server located?', ru: 'Где расположен сервер?' },
  'faq.a5': { en: 'Dedicated servers in Germany. Average ping for EU players: 15-40ms.', ru: 'Выделенные серверы в Германии. Средний пинг для EU: 15-40мс.' },
  'classes.title': { en: 'Choose your class', ru: 'Выбери свой класс' },
  'classes.desc': { en: 'Each class has a unique role on the battlefield. Pick wisely.', ru: 'У каждого класса своя роль на поле боя. Выбирай с умом.' },
  'timer.next': { en: 'Next siege', ru: 'Следующая осада' },
  'timer.days': { en: 'd', ru: 'д' },
  'timer.hours': { en: 'h', ru: 'ч' },
  'timer.min': { en: 'm', ru: 'м' },
  'timer.sec': { en: 's', ru: 'с' },
  'wiki.title': { en: 'Server info', ru: 'Информация о сервере' },
  'wiki.desc': { en: 'Everything you need to know before entering Atreia.', ru: 'Всё, что нужно знать перед входом в Атрею.' },
  'wiki.rates': { en: 'Rates', ru: 'Рейты' },
  'wiki.general': { en: 'General', ru: 'Общее' },
  'wiki.pvp': { en: 'PvP & Abyss', ru: 'PvP и Бездна' },
  'wiki.craft': { en: 'Craft & Economy', ru: 'Крафт и Экономика' },
  'wiki.instances': { en: 'Instances', ru: 'Инстансы' },
  'wiki.other': { en: 'Other', ru: 'Другое' },
  'wiki.back': { en: 'Back to home', ru: 'На главную' },
  'schedule.title': { en: 'Schedule', ru: 'Расписание' },
  'schedule.desc': { en: 'All times GMT+1 (CET). Fortress vulnerability windows and battleground queues.', ru: 'Все время по GMT+1 (CET). Окна уязвимости крепостей и очереди на поля боя.' },
  'schedule.sieges': { en: 'Sieges', ru: 'Осады' },
  'schedule.dredgion': { en: 'Dredgion', ru: 'Дредгион' },
  'schedule.rifts': { en: 'Rifts', ru: 'Разломы' },
  'schedule.time': { en: 'Time', ru: 'Время' },
  'schedule.day': { en: 'Day', ru: 'День' },
  'schedule.direction': { en: 'Direction', ru: 'Направление' },
  'schedule.back': { en: 'Back to home', ru: 'На главную' },
}

export function useLang() {
  function t(key: string): string {
    return translations[key]?.[currentLang.value] ?? key
  }

  function setLang(lang: Lang) {
    currentLang.value = lang
  }

  return { lang: currentLang, t, setLang }
}
